swagger: "2.0"

################################################################################
#                              API Information                                 #
################################################################################

info:
  version: "0.0.1"
  title: Rune Platform API
  description: |
    The Rune Platform API is the full suite of webservices available that drive 
    Rune's cloud ecosystem. 
    
    ## Authentication
    
    ## Limits
    
    ## Structure
    
    

################################################################################
#                  Host, Base Path, Schemes and Content Types                  #
################################################################################
host: localhost:10010
basePath: /v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
  
################################################################################
#                                   Tags                                       #
################################################################################
tags:
  - name: Devices
    description:  |
      Device related requests
  - name: Users
  - name: Analytics

################################################################################
#                                  Security                                    #
################################################################################
securityDefinitions:
  oauth:
    type: oauth2
    flow: implicit
    authorizationUrl: https://api.rune.io/oauth/authorize/?client_id=CLIENT-ID&redirect_uri=REDIRECT-URI&response_type=token
    scopes:
      basic: |
       to read any and all data related to a user (e.g. devices owned, personas, location, profile info etc.) (granted by default)
      device: to act on a user device only
      analytics: to act on a user's usage analytics
  key:
    type: apiKey
    in: query
    name: access_token
security:
  - oauth:
    - basic
    - device
    - analytics
  - key: []

################################################################################
#                                   Parameters                                 #
################################################################################
parameters:
  device-id:
    name: device-id
    in: path
    description: The device/thing identifier number
    type: string
    required: true
    
################################################################################
#                                           Paths                              #
################################################################################
paths:
  /devices/{device-id}:
    parameters:
      - $ref: '#/parameters/device-id'
    # binds a127 app logic to a route
    x-swagger-router-controller: devices
    get:
      description: Returns mac address and certificate bundle for a given device
      # used as the method name of the controller
      operationId: getdevicecerts
      tags:
        - Devices
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/DeviceCertsResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /devices:
    # binds a127 app logic to a route
    x-swagger-router-controller: devices
    post:
      description: Add a new device MAC. Implicitly generates a corresponding cert bundle
      # used as the method name of the controller
      operationId: postdevicecerts
      parameters:
        - name: macaddr
          in: body
          description: MAC address to create
          schema:
            type: string
      tags:
        - Devices
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/DeviceCertsResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  DeviceCertsResponse:
    required:
      - message
    properties:
      message:
        type: string
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
